//Sublet App for the New TuftsLife
//This code is (C)2013 Fred Teumer

function Listing() {
	//a unique id is attached to each listing, this is private
	var id;
	
	//this variable says whether this has been filled and will remove this from the list
	//if a specific sublet is 'filled'
	var filled;
	
	//group of easy to use vars that hold address
	this.lister;
	this.add_st;
	this.add_city;
	this.add_zip;
	
	this.description;
	//images is an array of up to (5) images of the residence
	this.images;
	this.rent;
	//contact information, must list email, phone is optional
	this.email;
	this.phone;
	
	this.listdate;
	this.startdate;
	this.enddate;
	
	//private function to initialize a new Listing
	var init = function(st, city, zip, description, rent, stm, std, sty, endm, endd, endy, name, email, 
	  phone, img, dat) {
		//id is generated by outside function
		id = genId();
		filled = false;
	
		this.add_st = st;
		this.add_city = city;
		this.add_zip = zip;
		this.description = description;
		this.images = null;
		this.rent = rent;
		this.startdate = stm.toString()+"/"+std.toString()+"/"+sty.toString();
		this.enddate = endm.toString()+"/"+endd.toString()+"/"+endy.toString();
		this.lister = lister;
		this.email = email;
		this.phone = phone;
		this.listdate = dat;
	}
	
	//public function used to view a listing
	this.view = function() {}
	
	this.list = function() {}
	
}
//master list of allListings. only works if filled == false
var allListings;
 
function init() {
	
	//sidebar
    var add = "<p class=\"button\" id=\"addButton\" onclick=\"openPopup(this, \'add\')\">Add Listing</p>";
    var rem = "<p class=\"button\" id=\"remButton\" \
      onclick=\"openPopup(this, \'rem\')\">Remove Listing</p>";
    $('#sidebar').append(add);
    $('#sidebar').append(rem);
    
   
    
    if(allListings == null){
	    $('#listings').append("<p>There doesn't seem to be anything here...</p>");
    }
	
}

function openPopup(item, type) {
	if(type == 'add'){
		$('#popupTitle').html("List Your Apartment");
		
		$('#popupBody').html("<form class=\"iform\" id=\"addForm\" action=\"\"> \
            Address: <input type=\"text\" maxlength=\"40\" name=\"address\" /><br /> \
            City/Zip: <input type=\"text\" name=\"city\" maxlength=\"25\" /> \
            <input type=\"text\" id=\"fzip\" name=\"zip\" maxlength=\"5\"/><br /> \
            Description: <textarea id=\"fdesc\" name=\"desc\" maxlength=\"250\" \
            rows=\"3\" cols=\"40\"></textarea> \
            Rent/Month: <input type=\"text\" id=\"frent\" name=\"rent\" maxlength=\"4\" /><br /> \
            Start Date (MM/DD/YYYY): <input type=\"text\" class=\"ftwo\" name=\"startm\" \
            	maxlength=\"2\" /> \
            / <input type=\"text\" class=\"ftwo\" name=\"startd\" maxlength=\"2\" /> \
            / <input type=\"text\" class=\"ffour\" name=\"starty\" maxlength=\"4\" /><br /> \
            End Date (MM/DD/YYYY): <input type=\"text\" class=\"ftwo\" name=\"endm\" maxlength=\"2\" /> \
            / <input type=\"text\" class=\"ftwo\" name=\"endd\" maxlength=\"2\" /> \
            / <input type=\"text\" class=\"ffour\" name=\"endy\" maxlength=\"4\" /><br /> \
            Name: <input type=\"text\" name=\"uname\" maxlength=\"40\" /><br /> \
            Email: <input type=\"email\" name=\"email\" maxlength=\"40\" /><br /> \
            Phone: <input type=\"text\" id=\"fphone\" name=\"phone\" maxlength=\"10\" /><br /> \
        </form>");
        
        $('#popupFoot').html("<button id=\"listButton\" class=\"btn btn-primary\" \
        	onclick=\"createListing()\" >List</button>");
        	//data-dismiss=\"modal\" aria-hidden=\"true\">List</button>");
        	
		$('#popup').modal();
	} 
	else if(type == 'rem'){
		$('#popupTitle').html("Remove Your Listing");
		
		$('#popupBody').html("<form class=\iform\" id=\"remForm\" action=\"\"> \
			Secret Code: <input type=\"text\" size=\"7\" id=\"frem\" name=\"remove\" /> \
			</form>");
			
		$('#popupFoot').html("<button id=\"remButton\" class=\"btn btn-primary\" \
        	onclick=\"remListing()\" data-dismiss=\"modal\" aria-hidden=\"true\">Remove Listing</button>");
        	
		$('#popup').modal();
	} 
	else if(type == 'view'){
		$('#popupTitle').html($(item).html());
		
		$('#popupFoot').html("<button id=\"closeButton\" class=\"btn btn-primary\" \
        	data-dismiss=\"modal\" aria-hidden=\"true\">Close</button>");
        	
		$('#popup').modal();
	}
}

function createListing(){
	newList = new Listing();
	
	var today = new Date();
	var dd = today.getDate();
	var mm = today.getMonth()+1; //January is 0!

	var yyyy = today.getFullYear();
	if(dd<10){dd='0'+dd} if(mm<10){mm='0'+mm} today = mm+'/'+dd+'/'+yyyy;
	console.log(today);
	
	newList.init($('#addForm').elements[0],$('#addForm').elements[1],$('#addForm').elements[2], 
	$('#addForm').elements[3],$('#addForm').elements[4],$('#addForm').elements[5],$('#addForm').elements[6],
	$('#addForm').elements[7],$('#addForm').elements[8],$('#addForm').elements[9],
	$('#addForm').elements[10],$('#addForm').elements[11],$('#addForm').elements[12],
	$('#addForm').elements[13], null, today);
}




//existing js code
//dont touch
function evenOutChildren(divID) {
    var hei = 0;
    $(divID).children().each(function (x) {
        //$(this).attr("top","60%");
    });
}

function sizing() {
    var h = $(window).height() - 2*$("header").height();
    var w = $(window).width();
    var mar = parseInt($("#content").css("margin-top"),10);
    if(w > 767){ //desktop
    	$("#sidebarcol").height((h-(mar/2))+"px");
    	$("#leftpage").height((h-mar)+"px");
    	$("#rightpage").height((h-mar)+"px");
    	//$("#leftarrow").offset().top = ($("#leftpage").offset.top+$("#leftpage").height()/2);
    }
    else{ //mobile
    	$("#sidebarcol").height(6*parseInt($(".categoryButton").height(),10));
    	$("#leftpage").height("0px");
    	$("#rightpage").height("0px");
    }

}

$(window).load(init);
$(document).ready(sizing);
$(window).resize(sizing);